const ar = {
  nav: { home: "الرئيسية", collection: "المجموعة", artists: "الفنانون", packaging: "العرض والتغليف", contact: "اتصل بنا", enquire: "استفسار" },
  hero: { label: "بيت فني عائلي", title1: "حيث يلتقي الفن", title2: "بالإيمان", subtitle: "خط عربي معاصر ولوحات مناظر طبيعية أصلية مصنوعة يدوياً في إندونيسيا.", cta: "استكشف المجموعة", ctaArtist: "تعرف على الفنانين", stat1: "أعمال أصلية", stat2: "معارض وطنية", stat3: "فنانون", scroll: "مرر" },
  featured: { label: "المعرض", title: "أعمال مختارة", subtitle: "لمحة من المجموعة المُنسقة.", viewAll: "عرض المجموعة الكاملة" },
  story: { label: "قصتنا", title: "بيت فني عائلي", text: "وُلد من حب مشترك للفن، معرض ريحان هو استوديو أم وابن متجذر في إندونيسيا. كل قطعة هي عمل فني أصلي مصنوع يدوياً بنية وصبر وروح.", meetArtists: "تعرف على الفنانين", raihanRole: "الخط العربي المعاصر", condroRole: "رسم المناظر الطبيعية" },
  cta: { label: "ابدأ مجموعتك", title: "ابدأ مجموعتك", subtitle: "كل عمل فني فريد من نوعه.", button: "استفسر عبر واتساب" },
  collection: { label: "مجموعة مُنسقة", title: "المجموعة", subtitle: "أعمال أصلية لريحان وكوندرو.", available: "متاح", total: "الإجمالي", allWorks: "جميع الأعمال", calligraphy: "خط عربي", landscape: "مناظر طبيعية", statusAll: "الكل", statusAvailable: "متاح", statusCollected: "مُقتنى", sortNewest: "الأحدث", sortAZ: "أ – ي", statusPrefix: "الحالة: ", sortPrefix: "الترتيب: ", noResults: "لا توجد أعمال.", clearFilters: "مسح المرشحات" },
  modal: { about: "عن العمل", details: "التفاصيل", shipping: "الشحن", noDescription: "لا يوجد وصف.", yearCreated: "سنة الإنشاء", medium: "الوسيط", category: "الفئة", size: "الحجم", dimensions: "الأبعاد", rarity: "عمل فريد", rarityLabel: "الندرة", frame: "الإطار", readyToHang: "جاهز للتعليق", authenticity: "الأصالة", packaging: "التغليف", needMore: "تحتاج مزيداً؟", contactWa: "تواصل عبر واتساب", deliveryCost: "تكلفة التوصيل", deliveryCostVal: "مجاني", deliveryTime: "وقت التوصيل", deliveryTimeVal: "٣-٧ أيام (محلي) · ١٤-٣٠ يوم (دولي)", returns: "الإرجاع", returnsVal: "تواصل معنا خلال ٣ أيام", handling: "المناولة", handlingVal: "محلي: مؤطر. دولي: ملفوف.", shipsFrom: "يُشحن من", enquireWa: "استفسر عبر واتساب", enquireSimilar: "استفسر عن أعمال مشابهة", collected: "مُقتنى", oneOfOne: "كل قطعة أصلية وفريدة" },
  card: { collected: "مُقتنى" },
  contact: { label: "اتصل بنا", title: "تواصل معنا", subtitle: "يسعدنا سماعك.", waTitle: "واتساب", waText: "أسرع طريقة للتواصل.", waCta: "إرسال رسالة", igTitle: "إنستغرام", igText: "تابع رحلة الاستوديو.", quote: "كل قطعة هي عمل فني أصلي." },
  artist: { label: "الفنانون", title1: "وراء كل ضربة،", title2: "قصة", intro: "معرض ريحان هو معرض فني عائلي شكّله جيلان من التفاني في الفن.", raihanLabel: "فنان ومؤسس", raihanBio1: "ريحان محمد فنان خط عربي تجريدي ومؤسس معرض ريحان.", raihanBio2: "نهجه يرفع الحروف العربية إلى عناصر بصرية حية.", raihanBio3: "كل عمل يولد عند تقاطع الإيمان والتعبير الإبداعي.", raihanMedium: "خط تجريدي · وسائط مختلطة", condroLabel: "فنانة", condroBio1: "كوندرو فنانة بصرية بدأت علاقتها بالرسم منذ الصغر.", condroBio2: "إنجازها الأول جاء عام ١٩٩٢.", condroBio3: "عادت للرسم بتفانٍ كامل عام ٢٠١٨.", condroBio4: "هي الجذر الذي ينمو منه هذا المعرض.", condroMedium: "زيت على قماش", exhibitions: "تاريخ المعارض", discoverTitle: "اكتشف أعمالهم", discoverText: "استكشف المجموعة الكاملة.", exploreCta: "استكشف المجموعة", abstractCalligraphy: "خط تجريدي", landscapeNature: "مناظر طبيعية" },
  footer: { tagline: "معرض فني عائلي. فن مصنوع يدوياً من إندونيسيا.", navigation: "التنقل", getInTouch: "تواصل معنا", rights: "جميع الحقوق محفوظة.", motto: "كل قطعة عمل فني أصلي" },
};
export default ar;
