const es = {
  nav: { home: "Inicio", collection: "Colección", artists: "Artistas", packaging: "Vista Previa & Embalaje", contact: "Contacto", enquire: "Consultar" },
  hero: { label: "Una Casa de Arte Familiar", title1: "Donde el Arte", title2: "Encuentra la Devoción", subtitle: "Caligrafía contemporánea original y pinturas de paisajes atmosféricos hechas a mano en Indonesia.", cta: "Explorar la Colección", ctaArtist: "Conocer a los Artistas", stat1: "Obras Originales", stat2: "Exposiciones Nacionales", stat3: "Artistas", scroll: "Desplazar" },
  featured: { label: "Galería", title: "Obras Seleccionadas", subtitle: "Una muestra curada de la colección.", viewAll: "Ver Colección Completa" },
  story: { label: "Nuestra Historia", title: "Una Casa de Arte Familiar", text: "Nacido de un amor compartido por el arte, Artgallery by Raihan es un estudio madre-hijo arraigado en Indonesia. Cada pieza es una obra de arte original hecha a mano con intención, paciencia y alma.", meetArtists: "Conocer a los Artistas", raihanRole: "Caligrafía Contemporánea", condroRole: "Pintura de Paisajes" },
  cta: { label: "Inicie Su Colección", title: "Inicie Su Colección", subtitle: "Cada obra es única. Contáctenos para discutir una pieza.", button: "Consultar vía WhatsApp" },
  collection: { label: "Colección Curada", title: "La Colección", subtitle: "Obras originales de Raihan y Condro P.S.", available: "disponible", total: "total", allWorks: "Todas las Obras", calligraphy: "Caligrafía", landscape: "Paisaje", statusAll: "Todos", statusAvailable: "Disponible", statusCollected: "Vendido", sortNewest: "Más Reciente", sortAZ: "A – Z", statusPrefix: "Estado: ", sortPrefix: "Ordenar: ", noResults: "No se encontraron obras.", clearFilters: "Limpiar filtros" },
  modal: { about: "Acerca de", details: "Detalles", shipping: "Envío", noDescription: "Sin descripción.", yearCreated: "Año de Creación", medium: "Medio", category: "Categoría", size: "Tamaño", dimensions: "Dimensiones", rarity: "Obra Única", rarityLabel: "Rareza", frame: "Marco", readyToHang: "Listo para Colgar", authenticity: "Autenticidad", packaging: "Embalaje", needMore: "¿Necesita más información?", contactWa: "Contactar vía WhatsApp", deliveryCost: "Costo de Envío", deliveryCostVal: "Gratis", deliveryTime: "Tiempo de Envío", deliveryTimeVal: "3-7 días hábiles (nacional) · 14-30 días hábiles (internacional)", returns: "Devoluciones", returnsVal: "Contáctenos dentro de 3 días", handling: "Manejo", handlingVal: "Nacional: Enmarcado. Internacional: Enrollado.", shipsFrom: "Enviado Desde", enquireWa: "Consultar vía WhatsApp", enquireSimilar: "Consultar Obras Similares", collected: "Vendido", oneOfOne: "Cada pieza es original y única" },
  card: { collected: "Vendido" },
  contact: { label: "Contacto", title: "Contáctenos", subtitle: "Nos encantaría saber de usted.", waTitle: "WhatsApp", waText: "La forma más rápida de contactarnos.", waCta: "Enviar Mensaje", igTitle: "Instagram", igText: "Siga nuestro viaje en el estudio.", quote: "Cada pieza es una obra de arte original hecha a mano." },
  artist: { label: "Los Artistas", title1: "Detrás de Cada Pincelada,", title2: "una Historia", intro: "Artgallery by Raihan es una galería familiar formada por dos generaciones de devoción al arte.", raihanLabel: "Artista y Fundador", raihanBio1: "Raihan Mohammad es un artista de caligrafía abstracta y fundador.", raihanBio2: "Su enfoque eleva las letras árabes a elementos visuales vivos.", raihanBio3: "Cada obra nace en la intersección de fe y expresión creativa.", raihanMedium: "Caligrafía Abstracta · Técnica Mixta", condroLabel: "Artista", condroBio1: "Condro, nacida en 1973, es una artista visual.", condroBio2: "Su primer logro importante llegó en 1992.", condroBio3: "En 2018 volvió a la pintura con plena dedicación.", condroBio4: "Ella es la raíz de la que crece esta galería.", condroMedium: "Óleo sobre Lienzo", exhibitions: "Historia de Exposiciones", discoverTitle: "Descubra Sus Obras", discoverText: "Explore la colección completa.", exploreCta: "Explorar la Colección", abstractCalligraphy: "Caligrafía Abstracta", landscapeNature: "Pintura de Paisajes y Naturaleza" },
  footer: { tagline: "Galería de arte familiar con arte hecho a mano desde Indonesia.", navigation: "Navegación", getInTouch: "Contacto", rights: "Todos los derechos reservados.", motto: "Cada pieza es una obra de arte original hecha a mano" },
};
export default es;
