const tr = {
  nav: { home: "Ana Sayfa", collection: "Koleksiyon", artists: "Sanatçılar", packaging: "Önizleme & Paketleme", contact: "İletişim", enquire: "Sorgula" },
  hero: { label: "Bir Aile Sanat Evi", title1: "Sanatın", title2: "Adanmışlıkla Buluştuğu Yer", subtitle: "Endonezya'dan el yapımı orijinal çağdaş hat sanatı ve atmosferik manzara resimleri.", cta: "Koleksiyonu Keşfet", ctaArtist: "Sanatçılarla Tanışın", stat1: "Orijinal Eser", stat2: "Ulusal Sergi", stat3: "Sanatçı", scroll: "Kaydır" },
  featured: { label: "Galeri", title: "Seçilmiş Eserler", subtitle: "Küratörlü koleksiyondan bir seçki.", viewAll: "Tüm Koleksiyonu Gör" },
  story: { label: "Hikayemiz", title: "Bir Aile Sanat Evi", text: "Sanata duyulan ortak sevgiden doğan Artgallery by Raihan, Endonezya kökenli bir anne-oğul stüdyosudur. Her parça niyet, sabır ve ruhla yaratılmış orijinal, el yapımı bir sanat eseridir.", meetArtists: "Sanatçılarla Tanışın", raihanRole: "Çağdaş Hat Sanatı", condroRole: "Manzara Resmi" },
  cta: { label: "Koleksiyonunuza Başlayın", title: "Koleksiyonunuza Başlayın", subtitle: "Her eser benzersizdir. Size hitap eden parçayı tartışmak için ulaşın.", button: "WhatsApp ile Sorgula" },
  collection: { label: "Küratörlü Koleksiyon", title: "Koleksiyon", subtitle: "Raihan ve Condro'nun orijinal eserleri.", available: "mevcut", total: "toplam", allWorks: "Tüm Eserler", calligraphy: "Hat Sanatı", landscape: "Manzara", statusAll: "Tümü", statusAvailable: "Mevcut", statusCollected: "Satılmış", sortNewest: "En Yeni", sortAZ: "A – Z", statusPrefix: "Durum: ", sortPrefix: "Sıralama: ", noResults: "Filtrelere uyan eser yok.", clearFilters: "Filtreleri temizle" },
  modal: { about: "Hakkında", details: "Detaylar", shipping: "Kargo", noDescription: "Açıklama yok.", yearCreated: "Yapım Yılı", medium: "Malzeme", category: "Kategori", size: "Boyut", dimensions: "Ölçüler", rarity: "Tek ve Benzersiz Eser", rarityLabel: "Nadirlik", frame: "Çerçeve", readyToHang: "Asılmaya Hazır", authenticity: "Orijinallik", packaging: "Paketleme", needMore: "Daha fazla bilgi?", contactWa: "WhatsApp ile iletişime geçin", deliveryCost: "Teslimat Ücreti", deliveryCostVal: "Ücretsiz", deliveryTime: "Teslimat Süresi", deliveryTimeVal: "3-7 iş günü (yurtiçi) · 14-30 iş günü (uluslararası)", returns: "İade", returnsVal: "Sorun varsa 3 gün içinde bize ulaşın", handling: "Taşıma", handlingVal: "Yurtiçi: Çerçeveli. Uluslararası: Tüpte.", shipsFrom: "Gönderim Yeri", enquireWa: "WhatsApp ile Sorgula", enquireSimilar: "Benzer Eserleri Sorgula", collected: "Satılmış", oneOfOne: "Her parça orijinal ve benzersiz" },
  card: { collected: "Satılmış" },
  contact: { label: "İletişim", title: "İletişime Geçin", subtitle: "Sizden haber almaktan mutluluk duyarız.", waTitle: "WhatsApp", waText: "Bize ulaşmanın en hızlı yolu.", waCta: "Mesaj Gönder", igTitle: "Instagram", igText: "Stüdyo yolculuğumuzu takip edin.", quote: "Her parça niyet, sabır ve ruhla yaratılmış el yapımı bir sanat eseridir." },
  artist: { label: "Sanatçılar", title1: "Her Fırça Darbesinin", title2: "Ardında Bir Hikaye", intro: "Artgallery by Raihan, iki neslin sanata adanmışlığıyla şekillenmiş bir aile sanat galerisidir.", raihanLabel: "Sanatçı & Kurucu", raihanBio1: "Raihan Mohammad, soyut hat sanatçısı ve Artgallery by Raihan'ın kurucusudur.", raihanBio2: "Yaklaşımı Arap harflerini canlı görsel unsurlara dönüştürür.", raihanBio3: "Her eser iman ve yaratıcı ifadenin kesişim noktasında doğar.", raihanMedium: "Soyut Hat · Karışık Teknik", condroLabel: "Sanatçı", condroBio1: "1973 doğumlu Condro, resimle ilişkisi bilinçli bir tercihten çok önce başlamış bir görsel sanatçıdır.", condroBio2: "İlk önemli başarısı 1992'de geldi.", condroBio3: "2018'de tam adanmışlıkla resme döndü.", condroBio4: "Bu galerinin büyüdüğü köktür.", condroMedium: "Tuval üzerine Yağlı Boya", exhibitions: "Sergi Geçmişi", discoverTitle: "Eserlerini Keşfet", discoverText: "Tam koleksiyonu keşfedin.", exploreCta: "Koleksiyonu Keşfet", abstractCalligraphy: "Soyut Hat Sanatı", landscapeNature: "Manzara & Doğa Resmi" },
  footer: { tagline: "Endonezya'dan el yapımı sanat sunan aile sanat galerisi.", navigation: "Gezinme", getInTouch: "İletişime Geçin", rights: "Tüm hakları saklıdır.", motto: "Her parça orijinal, el yapımı bir sanat eseridir" },
};
export default tr;
